services:
  mysql:
    container_name: springboot_template_mysql
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: springboot_template
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - springboot-template
networks:
  springboot-template:
    name: springboot-template
    driver: bridge
